services:
  traefik:
    image: traefik:3.1.2
    command: --api.insecure=true --providers.docker --tracing.otlp=true --tracing.otlp.grpc.endpoint=dashboard:18889 --tracing.otlp.grpc.insecure=true
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - dashboard

  mongo:
    image: mongo:latest

  rabbit:
    image: rabbitmq:latest

  dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.1.0
    labels:
      - 'traefik.http.routers.dashboardUI.rule=Host(`dashboardUI.localhost`)'
      - 'traefik.http.routers.dashboardUI.service=dashboardUI'
      - 'traefik.http.services.dashboardUI.loadbalancer.server.port=18888'
      - 'traefik.http.routers.dashboardOtlpGrpc.rule=Host(`dashboard-otlp-grpc.localhost`)'
      - 'traefik.http.routers.dashboardOtlpGrpc.service=dashboardOtlpGrpc'
      - 'traefik.http.services.dashboardOtlpGrpc.loadbalancer.server.port=18889'
      - 'traefik.http.routers.dashboardOtlpHttp.rule=Host(`dashboard-otlp-http.localhost`)'
      - 'traefik.http.routers.dashboardOtlpHttp.service=dashboardOtlpHttp'
      - 'traefik.http.services.dashboardOtlpHttp.loadbalancer.server.port=18890'


  command-processor:
    build:
      dockerfile: ./packages/demo/orchestrated/command-processor/Dockerfile
      context: ../../..
    depends_on:
      - mongo
      - rabbit
      - dashboard
    develop:
      watch:
        - action: sync
          path: ./command-processor
          target: /src/packages/demo/orchestrated/command-processor
    labels:
      - 'traefik.http.routers.command-processor-orchestrated.rule=Host(`commands.localhost`)'
    environment:
      EXPRESS_PORT: '80'
      MONGO_URL: 'mongodb://mongo:27017'
      RABBIT_URL: 'amqp://rabbit'
      LOG_LEVEL: 'trace'

  readmodel-customers:
    build:
      dockerfile: ./packages/demo/orchestrated/readmodel-customers/Dockerfile
      context: ../../..
    depends_on:
      - mongo
      - rabbit
      - change-notifier
      - dashboard
    develop:
      watch:
        - action: sync
          path: ./readmodel-customers
          target: /src/packages/demo/orchestrated/readmodel-customers
    labels:
      - 'traefik.http.routers.readmodel-customers-orchestrated.rule=Host(`rm-customers.localhost`)'
    environment:
      EXPRESS_PORT: '80'
      MONGO_URL: 'mongodb://mongo:27017'
      MONGO_DATABASE: 'readmodel-customers'
      RABBIT_URL: 'amqp://rabbit'
      CHANGENOTIFICATION_FETCH_URL: 'http://change-notifier/change'
      COMMAND_URL: 'http://command-processor/api/command'
      LOG_LEVEL: 'trace'

  readmodel-orders:
    build:
      dockerfile: ./packages/demo/orchestrated/readmodel-orders/Dockerfile
      context: ../../..
    depends_on:
      - mongo
      - rabbit
      - change-notifier
      - dashboard
    develop:
      watch:
        - action: sync
          path: ./readmodel-orders
          target: /src/packages/demo/orchestrated/readmodel-orders
    labels:
      - 'traefik.http.routers.readmodel-orders-orchestrated.rule=Host(`rm-orders.localhost`)'
    environment:
      EXPRESS_PORT: '80'
      MONGO_URL: 'mongodb://mongo:27017'
      MONGO_DATABASE: 'readmodel-orders'
      RABBIT_URL: 'amqp://rabbit'
      CHANGENOTIFICATION_FETCH_URL: 'http://change-notifier/change'
      COMMAND_URL: 'http://command-processor/api/command'
      LOG_LEVEL: 'trace'

  readmodel-dotnet:
    build:
      dockerfile: ./packages/demo/orchestrated/readmodel-dotnet/Dockerfile
      context: ../../..
    depends_on:
      - rabbit
    environment:
      RABBIT_URL: 'amqp://rabbit'
      DOTNET_WATCH_RESTART_ON_RUDE_EDIT: 1
    labels:
      - 'traefik.http.routers.readmodel-dotnet-orchestrated.rule=Host(`rm-dotnet.localhost`)'
    develop:
      watch:
        - action: sync
          path: ./readmodel-dotnet
          target: /src/packages/demo/orchestrated/readmodel-dotnet

  change-notifier:
    build:
      dockerfile: ./packages/demo/orchestrated/change-notifier/Dockerfile
      context: ../../..
    depends_on:
      - dashboard
    develop:
      watch:
        - action: sync
          path: ./change-notifier
          target: /src/packages/demo/orchestrated/change-notifier
    labels:
      - 'traefik.http.routers.change-notifier-orchestrated.rule=Host(`change-notifier.localhost`)'
    environment:
      EXPRESS_PORT: '80'
      LOG_LEVEL: 'trace'

  frontend-react:
    build:
      dockerfile: ./packages/demo/orchestrated/frontend-react/Dockerfile
      context: ../../..
    depends_on:
      - command-processor
      - readmodel-customers
      - readmodel-orders
      - change-notifier
    develop:
      watch:
        - action: sync
          path: ./frontend-react/src
          target: /src/packages/demo/orchestrated/frontend-react/src
    labels:
      - 'traefik.http.routers.frontend-react-orchestrated.rule=Host(`react.localhost`)'
    environment:
      VITE_RM_CUSTOMERS_URL: 'http://rm-customers.localhost'
      VITE_RM_ORDERS_URL: 'http://rm-orders.localhost'
      VITE_COMMAND_URL: 'http://commands.localhost/api/command'
      VITE_CHANGENOTIFIER_URL: 'http://change-notifier.localhost'

  frontend-svelte:
    build:
      dockerfile: ./packages/demo/orchestrated/frontend-svelte/Dockerfile
      context: ../../..
    depends_on:
      - command-processor
      - readmodel-customers
      - readmodel-orders
      - change-notifier
    develop:
      watch:
        - action: sync
          path: ./frontend-svelte/src
          target: /src/packages/demo/orchestrated/frontend-svelte/src
    labels:
      - 'traefik.http.routers.frontend-svelte-orchestrated.rule=Host(`svelte.localhost`)'
    environment:
      VITE_RM_CUSTOMERS_URL: 'http://rm-customers.localhost'
      VITE_RM_ORDERS_URL: 'http://rm-orders.localhost'
      VITE_COMMAND_URL: 'http://commands.localhost/api/command'
      VITE_CHANGENOTIFIER_URL: 'http://change-notifier.localhost'
