version: '3.8'

services:
  traefik:
    image: traefik:3.2.1
    command: --api.insecure=true --providers.docker
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo:latest

  rabbit:
    image: rabbitmq:latest

  command-processor:
    build:
      dockerfile: ./packages/demo/orchestrated/command-processor/Dockerfile
      context: ../../..
    depends_on:
      - mongo
      - rabbit
    volumes:
      - ./command-processor:/src/packages/demo/orchestrated/command-processor
    environment:
      EXPRESS_PORT: '80'
      MONGO_URL: 'mongodb://mongo:27017'
      RABBIT_URL: 'amqp://rabbit'
      LOG_LEVEL: 'trace'
    labels:
      - 'traefik.http.routers.command-processor-orchestrated.rule=Host(`commands.localhost`)'

  readmodel-customers:
    build:
      dockerfile: ./packages/demo/orchestrated/readmodel-customers/Dockerfile
      context: ../../..
    depends_on:
      - mongo
      - rabbit
      - change-notifier
    volumes:
      - ./readmodel-customers:/src/packages/demo/orchestrated/readmodel-customers
    environment:
      EXPRESS_PORT: '80'
      MONGO_URL: 'mongodb://mongo:27017'
      MONGO_DATABASE: 'readmodel-customers'
      RABBIT_URL: 'amqp://rabbit'
      CHANGENOTIFICATION_FETCH_URL: 'http://change-notifier/change'
      COMMAND_URL: 'http://command-processor/api/command'
      LOG_LEVEL: 'trace'
    labels:
      - 'traefik.http.routers.readmodel-customers-orchestrated.rule=Host(`rm-customers.localhost`)'

  readmodel-orders:
    build:
      dockerfile: ./packages/demo/orchestrated/readmodel-orders/Dockerfile
      context: ../../..
    depends_on:
      - mongo
      - rabbit
      - change-notifier
    volumes:
      - ./readmodel-orders:/src/packages/demo/orchestrated/readmodel-orders
    environment:
      EXPRESS_PORT: '80'
      MONGO_URL: 'mongodb://mongo:27017'
      MONGO_DATABASE: 'readmodel-orders'
      RABBIT_URL: 'amqp://rabbit'
      CHANGENOTIFICATION_FETCH_URL: 'http://change-notifier/change'
      COMMAND_URL: 'http://command-processor/api/command'
      LOG_LEVEL: 'trace'
    labels:
      - 'traefik.http.routers.readmodel-orders-orchestrated.rule=Host(`rm-orders.localhost`)'

  readmodel-dotnet:
    build:
      dockerfile: ./packages/demo/orchestrated/readmodel-dotnet/Dockerfile
      context: ../../..
    depends_on:
      - rabbit
    environment:
      RABBIT_URL: 'amqp://rabbit'

  change-notifier:
    build:
      dockerfile: ./packages/demo/orchestrated/change-notifier/Dockerfile
      context: ../../..
    volumes:
      - ./change-notifier:/src/packages/demo/orchestrated/change-notifier
    environment:
      EXPRESS_PORT: '80'
      LOG_LEVEL: 'trace'
    labels:
      - 'traefik.http.routers.change-notifier-orchestrated.rule=Host(`change-notifier.localhost`)'

  frontend-react:
    build:
      dockerfile: ./packages/demo/orchestrated/frontend-react/Dockerfile
      context: ../../..
    depends_on:
      - command-processor
      - readmodel-customers
      - readmodel-orders
      - change-notifier
    volumes:
      - ./frontend-react/src:/src/packages/demo/orchestrated/frontend-react/src
    environment:
      VITE_RM_CUSTOMERS_URL: 'http://rm-customers.localhost'
      VITE_RM_ORDERS_URL: 'http://rm-orders.localhost'
      VITE_COMMAND_URL: 'http://commands.localhost/api/command'
      VITE_CHANGENOTIFIER_URL: 'http://change-notifier.localhost'
    labels:
      - 'traefik.http.routers.frontend-react-orchestrated.rule=Host(`react.localhost`)'

  frontend-svelte:
    build:
      dockerfile: ./packages/demo/orchestrated/frontend-svelte/Dockerfile
      context: ../../..
    depends_on:
      - command-processor
      - readmodel-customers
      - readmodel-orders
      - change-notifier
    volumes:
      - ./frontend-svelte/src:/src/packages/demo/orchestrated/frontend-svelte/src
    environment:
      VITE_RM_CUSTOMERS_URL: 'http://rm-customers.localhost'
      VITE_RM_ORDERS_URL: 'http://rm-orders.localhost'
      VITE_COMMAND_URL: 'http://commands.localhost/api/command'
      VITE_CHANGENOTIFIER_URL: 'http://change-notifier.localhost'
    labels:
      - 'traefik.http.routers.frontend-svelte-orchestrated.rule=Host(`svelte.localhost`)'
